# TODO: create a shared image used by all containers
services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "16443:443"
    networks:
      - transcendence
    depends_on:
      - users
      - jwt
      - blockchain
      - game
      - avatars
      - friends
      - presences
    restart: unless-stopped

  redis:
    container_name: redis
    build: ./redis-service
    env_file:
      - ./.env
    networks:
      - transcendence
    volumes:
      - ./redis-service/data:/data
    restart: unless-stopped

  users:
    container_name: users
    build: ./users-service
    env_file:
      - ./.env
      - ./users-service/.env
    networks:
      - transcendence
    volumes:
      - ./users-service/database:/app/database
    restart: unless-stopped

  jwt:
    container_name: jwt
    build: ./jwt-service
    env_file:
      - ./.env
      - ./jwt-service/.env
    networks:
      - transcendence
    restart: unless-stopped

  blockchain:
    container_name: blockchain
    build: ./blockchain-service
    env_file:
      - ./.env
      - ./blockchain-service/.env
    networks:
      - transcendence
    restart: unless-stopped

  game:
    container_name: game
    build: ./game-service
    env_file:
      - ./.env
      - ./game-service/.env
    networks:
      - transcendence
    restart: unless-stopped

  avatars:
    container_name: avatars
    build: ./avatars-service
    env_file:
      - ./.env
      - ./avatars-service/.env
    networks:
      - transcendence
    volumes:
      - ./avatars-service/database:/app/database
      - ./avatars-service/avatars:/app/avatars
    restart: unless-stopped

  friends:
    container_name: friends
    build: ./friends-service
    env_file:
      - ./.env
    networks:
      - transcendence
    volumes:
      - ./friends-service/database:/app/database
    restart: unless-stopped

  presences:
    container_name: presences
    build: ./presences-service
    env_file:
      - ./.env
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
