# TODO: create a shared image used by all containers
services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
    networks:
      - transcendence

  users:
    container_name: users
    build: ./users-service
    env_file:
      - ./.env
      - ./users-service/.env
    networks:
      - transcendence
    volumes:
      - ./database:/app/database

  jwt:
    container_name: jwt
    build: ./jwt-service
    env_file:
      - ./.env
      - ./jwt-service/.env
    networks:
      - transcendence

  blockchain:
    container_name: blockchain
    build: ./blockchain-service
    env_file:
      - ./.env
      - ./blockchain-service/.env
    networks:
      - transcendence

  game:
    container_name: game
    build: ./game-service
    env_file:
      - ./.env
      - ./game-service/.env
    networks:
      - transcendence
    ports:
      - "8080:8080"
      - "8081:8081"

networks:
  transcendence:
