services:
  nginx:
    container_name: nginx
    build: ./nginx/
    ports:
      - "80:80"
    networks:
      - users

  users:
    container_name: users
    build: ./users-service
    env_file:
      - ./.env
      - ./users-service/.env
    networks:
      - users
    volumes:
      - ./users-service/database:/app/database

networks:
  users: