services:
  nginx:
    container_name: frontend
    build: ./frontend/
    ports:
      - "80:80"
    networks:
      - front_to_back
    depends_on:
      - backend

  backend:
    container_name: backend
    build: ./backend/
    networks:
      - front_to_back

networks:
  front_to_back:
    driver: bridge
  block_to_back:
    driver: bridge
