openapi: 3.0.0
info:
  title: Auth Service – ft_transcendence
  version: 1.0.0
  description: API d’authentification basée sur Fastify avec JWT stateless.

servers:
  - url: http://localhost:4000
    description: Serveur local

paths:
  /auth/register:
    post:
      summary: Créer un nouvel utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: azerty123
      responses:
        '201':
          description: JWT access + refresh token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '409':
          description: Email déjà enregistré

  /auth/login:
    post:
      summary: Connecter un utilisateur existant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  example: test@example.com
                password:
                  type: string
                  example: azerty123
      responses:
        '200':
          description: Access + refresh token ou tempToken si 2FA activé
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      accessToken:
                        type: string
                      refreshToken:
                        type: string
                  - type: object
                    properties:
                      tempToken:
                        type: string
        '401':
          description: Email ou mot de passe invalide

  /auth/2fa/login:
    post:
      summary: Vérifie un code 2FA et retourne les tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - tempToken
                - code
              properties:
                tempToken:
                  type: string
                code:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: Retourne access + refresh token si code correct
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '401':
          description: Code invalide ou expiré

  /auth/2fa/setup:
    post:
      summary: Génère un QR code et une clé manuelle pour configurer le 2FA
      security:
        - bearerAuth: []
      responses:
        '200':
          description: QR Code et clé 2FA retournés
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrCode:
                    type: string
                    example: data:image/png;base64,iVBOR...
                  manualKey:
                    type: string
                    example: ABCDEFGHIJKL123456

  /auth/2fa/verify:
    post:
      summary: Active le 2FA après configuration
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
                  example: "123456"
      responses:
        '200':
          description: 2FA activé
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 2FA successfully enabled
        '401':
          description: Code invalide

  /auth/2fa/status:
    get:
      summary: Vérifie si 2FA est activé pour l’utilisateur
      security:
        - bearerAuth: []
      responses:
        '200':
          description: État du 2FA
          content:
            application/json:
              schema:
                type: object
                properties:
                  is2faEnabled:
                    type: boolean

  /auth/refresh:
    post:
      summary: Rafraîchit les tokens
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refreshToken
              properties:
                refreshToken:
                  type: string
      responses:
        '200':
          description: Nouveau access + refresh token
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
        '401':
          description: Refresh token invalide

  /auth/me:
    get:
      summary: Retourne les infos de l’utilisateur connecté
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Infos de l’utilisateur
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      iat:
                        type: integer
        '401':
          description: Token invalide ou manquant

  /auth/verify-token:
    get:
      summary: Vérifie la validité du token
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Token valide
          content:
            application/json:
              schema:
                type: object
                properties:
                  valid:
                    type: boolean
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                      email:
                        type: string
                      iat:
                        type: integer
        '401':
          description: Token invalide ou manquant

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
