server {
	  listen 443 ssl;
    server_name elsalmajori.games;

    ssl_certificate           /etc/ssl/elsalmajori/cert.pem;
    ssl_certificate_key       /etc/ssl/elsalmajori/key.pem;
    ssl_trusted_certificate   /etc/ssl/elsalmajori/chain.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

	location / {
		root /app/public/;
		index index.html;
	}

	location /users {
		proxy_pass http://users:3000/users;
	}

	location /register {
		proxy_pass http://users:3000/register;
	}

	location /login {
		proxy_pass http://users:3000/login;
	}

	location /me {
		proxy_pass http://users:3000/me;
	}
    
    location /add-player {
        proxy_pass http://blockchain:3001/add-player;
    }

    location /report-match {
        proxy_pass http://blockchain:3001/report-match;
    }
}
