server {
	listen 80 default_server;

	location / {
		root /public/;
		index index.html;
	}

	location /api/ {
		proxy_pass http://users:3000/users;
	}

	location /users {
		proxy_pass http://users:3000/users;
	}
}
