server {
	listen 80 default_server;

	location / {
		root /html/;
		index index.html;
	}

	location /users {
		proxy_pass http://users:3000/users;
	}

	location /register {
		proxy_pass http://users:3000/register;
	}

	location /login {
		proxy_pass http://users:3000/login;
	}

	location /me {
		proxy_pass http://users:3000/me;
	}
}