openapi: 3.0.0
info:
  title: 2FA Service API
  version: 1.0.0
  description: |
    This service provides two-factor authentication (2FA) endpoints
    such as enabling 2FA, verifying tokens, and checking if 2FA is required.

servers:
  - url: http://localhost:4000

paths:
  /2fa/status:
    get:
      summary: Check if 2FA is required for an address
      tags:
        - 2FA
      parameters:
        - in: query
          name: address
          required: true
          schema:
            type: string
          description: Wallet address to check
      responses:
        '200':
          description: 2FA status
          content:
            application/json:
              schema:
                type: object
                properties:
                  is2faRequired:
                    type: boolean
        '400':
          description: Missing or invalid address

  /2fa/verify:
    post:
      summary: Verify a 2FA token
      tags:
        - 2FA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
                token:
                  type: string
              required:
                - address
                - token
      responses:
        '200':
          description: Token is valid
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '400':
          description: Missing fields
        '401':
          description: Invalid token

  /2fa/enable:
    post:
      summary: Generate a new 2FA secret and QR code
      tags:
        - 2FA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                address:
                  type: string
              required:
                - address
      responses:
        '200':
          description: QR code and secret returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  qrCode:
                    type: string
                    format: uri
                    description: Data URL of the QR code
                  secret:
                    type: string
                    description: Base32 secret (for testing only)
        '400':
          description: Missing address
        '500':
          description: QR code generation failed
