openapi: 3.0.3
info:
  title: PongChain API
  description: API REST pour interagir avec le MasterContract
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /add-player:
    post:
      summary: Ajouter un joueur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, address]
              properties:
                name:
                  type: string
                address:
                  type: string
      responses:
        200:
          description: Joueur ajouté avec succès
  /report-match:
    post:
      summary: Déclarer un match
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [player1, player2, matchId, player1Score, player2Score, winner]
              properties:
                player1:
                  type: string
                player2:
                  type: string
                matchId:
                  type: integer
                player1Score:
                  type: integer
                player2Score:
                  type: integer
                winner:
                  type: string
      responses:
        200:
          description: Match déclaré
  /report-tournament:
    post:
      summary: Déclarer un tournoi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [endTimestamp, matchIds, winner, tournamentTokenIds]
              properties:
                endTimestamp:
                  type: integer
                matchIds:
                  type: array
                  items:
                    type: integer
                winner:
                  type: string
                tournamentTokenIds:
                  type: integer
      responses:
        200:
          description: Tournoi enregistré
  /player/{name}:
    get:
      summary: Adresse d’un joueur
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Adresse Ethereum du joueur
  /match/player/{name}:
    get:
      summary: Matchs joués par un joueur
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Liste des matchs
  /match/winner/{address}:
    get:
      summary: Matchs gagnés par une adresse
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Matchs gagnés
  /match/{id}:
    get:
      summary: Détails d’un match
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Informations du match
  /tournament/{id}:
    get:
      summary: Détails d’un tournoi
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Informations du tournoi
  /tournament/winner/{address}:
    get:
      summary: Tournois gagnés par une adresse
      parameters:
        - name: address
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Liste des tournois gagnés
  /nft/goat/299:
    get:
      summary: Propriétaire du GOAT NFT
      responses:
        200:
          description: Adresse du propriétaire
  /nft/tournament/{tournamentId}:
    get:
      summary: Propriétaire d’un NFT de tournoi
      parameters:
        - name: tournamentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Adresse du propriétaire du NFT
